apiVersion: v1

clusters: 
- cluster:
    certificate-authority: /root/Kubernetes_keys/ca.crt 
    server: https://192.168.99.100:8443
  name: minikubec

contexts:
- context: 
    cluster: minikubec
    user: UserMinikube
  name: ContextMinikube
    
current-context: ContextMinikube
kind: Config
preferences: {}
users: 
- user: 
    client-certificate: /root/Kubernetes_keys/client.crt
    client-key: /root/Kubernetes_keys/client.key
  name: UserMinikube


