apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-dp

spec:
  strategy:
    type: Recreate 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      time : prac
  template: 
    metadata: 
      name: mysql-pod
      labels: 
        app: mysql
        time: prac   
    spec:
      containers:
      - name: con1
        image: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: secretdb
               key: syspass
         - name: MYSQL_DATABASE
           value: mysql1
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef: 
               name: secretdb
               key: username
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: secretdb
               key: password
        volumeMounts:
              - name: vol1
                mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql 
      volumes: 
      
       - persistentVolumeClaim:
           claimName: mypvc1
         name: vol1 


