apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
 - name: kustom-db
   literals:
     - username=Ishita
     - password=redhat
     - syspass=redhat
     
resources:
     - deployment_mysql.yml
     - deployment_wordpress.yml
