--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: rcweb
spec: 
  replicas: 3
  selector: 
    con: india
  template: 
    metadata: 
      name: podrc
      labels: 
        con: india 
    spec: 
      containers: 
      - image: vimal13/apache-webserver-php
        name: mycon1
