apiVersion: apps/v1
kind: ReplicaSet

metadata: 
  name: rs1
 
spec:
  replicas: 3
  selector: 
    matchExpressions:
      - {key: con, operator: In, values: [India]}
  template:
    metadata:
      name: podrs
      labels:
         con: India
    spec:      
      containers:
      - name: con1
        image: vimal13/apache-webserver-php 