apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: wordpress-rs

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      time : prac
  template: 
    metadata: 
      name: wordpress-pod
      labels: 
        app: wordpress
        time: prac   
    spec:
      containers:
      - name: con1
        image: wordpress
        env: 
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
               name: wordsecret
               key: host
        - name: WORDPRESS_DB_USER
          valueFrom:  
            secretKeyRef:
               name: secretdb
               key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
               name: secretdb
               key: password
        - name: WORDPRESS_DB_NAME
          value: mysql1  
        - name: WORDPRESS_TABLE_PREFIX
          value: db_info
        - name: WORDPRESS_DEBUG
          value: "1"
        ports: 
        - name: wordpress
          containerPort: 80
